namespace :clickup do
  desc "Remove all cards and boards imported from Fireflies Autogenerated"
  task :remove_fireflies => :environment do
    account = Import::Context.account
    system_user = account.system_user
    old_current_user = Current.user
    Current.user = system_user

    puts "🔍 Finding Fireflies Autogenerated items..."
    
    # Find all imported tasks from Fireflies Autogenerated
    # Check both list_name field and raw_payload JSON
    fireflies_task_ids = Set.new
    
    # Search by list_name
    ImportedClickupTask.where(account: account)
      .where("LOWER(list_name) LIKE ?", "%fireflies%")
      .where("LOWER(list_name) LIKE ?", "%autogenerated%")
      .pluck(:id).each { |id| fireflies_task_ids << id }
    
    # Search in raw_payload JSON
    require "json"
    ImportedClickupTask.where(account: account).find_each do |task|
      begin
        next unless task.raw_payload
        payload = task.raw_payload.is_a?(String) ? JSON.parse(task.raw_payload) : task.raw_payload
        list_name = payload["List Name"] || payload[" List Name"]
        if list_name&.downcase&.include?("fireflies") && list_name&.downcase&.include?("autogenerated")
          fireflies_task_ids << task.id
        end
      rescue => e
        # Skip if JSON parsing fails
      end
    end
    
    fireflies_tasks = ImportedClickupTask.where(id: fireflies_task_ids.to_a).includes(:card)
    
    puts "Found #{fireflies_tasks.count} imported tasks from Fireflies Autogenerated"
    
    # Also find cards directly by description content (fireflies.ai links)
    puts "🔍 Finding cards with fireflies.ai in description..."
    fireflies_cards = Card
      .joins(:board)
      .where(boards: { account: account })
      .joins("LEFT JOIN action_text_rich_texts ON action_text_rich_texts.record_type = 'Card' AND action_text_rich_texts.record_id = cards.id AND action_text_rich_texts.name = 'description'")
      .where("action_text_rich_texts.body LIKE ?", "%fireflies.ai%")
    
    puts "Found #{fireflies_cards.count} cards with fireflies.ai in description"

    deleted_cards = 0
    deleted_boards = Set.new

    # Delete cards from ImportedClickupTask records
    fireflies_tasks.find_each do |imported_task|
      if imported_task.card
        board = imported_task.card.board
        card_number = imported_task.card.number
        card = imported_task.card
        
        begin
          # Delete associated records first to avoid foreign key constraints
          # The card model has dependent: :destroy on most associations, but we'll be explicit
          card.comments.destroy_all
          card.assignments.destroy_all
          card.events.destroy_all
          card.taggings.destroy_all
          card.steps.destroy_all
          card.pins.destroy_all
          card.watches.destroy_all
          
          # Delete the card itself
          card.destroy
          
          if card.destroyed?
            deleted_cards += 1
            deleted_boards << board.id
            puts "  ✓ Deleted card ##{card_number} from board '#{board.name}'"
          else
            puts "  ✗ Failed to delete card ##{card_number}: #{card.errors.full_messages.join(', ')}"
          end
        rescue => e
          puts "  ✗ Error deleting card ##{card_number}: #{e.message}"
        end
      end
      
      # Delete the imported task record
      imported_task.destroy!
    end
    
    # Delete cards found by description search
    fireflies_cards.find_each do |card|
      board = card.board
      card_number = card.number
      
      begin
        # Delete associated records first to avoid foreign key constraints
        card.comments.destroy_all
        card.assignments.destroy_all
        card.events.destroy_all
        card.taggings.destroy_all
        card.steps.destroy_all
        card.pins.destroy_all
        card.watches.destroy_all
        
        # Delete the card itself
        card.destroy
        
        if card.destroyed?
          deleted_cards += 1
          deleted_boards << board.id
          puts "  ✓ Deleted card ##{card_number} from board '#{board.name}'"
        else
          puts "  ✗ Failed to delete card ##{card_number}: #{card.errors.full_messages.join(', ')}"
        end
      rescue => e
        puts "  ✗ Error deleting card ##{card_number}: #{e.message}"
      end
    end

    # Check if any boards are now empty and can be deleted
    deleted_board_count = 0
    deleted_boards.each do |board_id|
      board = Board.find_by(id: board_id)
      next unless board
      
      if board.cards.count == 0
        begin
          board_name = board.name
          board.destroy!
          deleted_board_count += 1
          puts "  ✓ Deleted empty board '#{board_name}'"
        rescue => e
          puts "  ✗ Error deleting board '#{board.name}': #{e.message}"
        end
      end
    end

    Current.user = old_current_user

    puts ""
    puts "✅ Cleanup completed!"
    puts "  Deleted cards: #{deleted_cards}"
    puts "  Deleted boards: #{deleted_board_count}"
    puts "  Remaining Fireflies tasks: #{ImportedClickupTask.where(account: account).where('LOWER(list_name) LIKE ?', '%fireflies%').where('LOWER(list_name) LIKE ?', '%autogenerated%').count}"
  end
end
