namespace :clickup do
  desc "Remove all cards and boards imported from Fireflies Autogenerated"
  task :remove_fireflies => :environment do
    account = Import::Context.account
    system_user = account.system_user
    old_current_user = Current.user
    Current.user = system_user

    puts "🔍 Finding Fireflies Autogenerated items..."
    
    # Find all imported tasks from Fireflies Autogenerated
    fireflies_tasks = ImportedClickupTask
      .where(account: account)
      .where("LOWER(list_name) LIKE ?", "%fireflies%")
      .where("LOWER(list_name) LIKE ?", "%autogenerated%")
      .includes(:card)

    puts "Found #{fireflies_tasks.count} imported tasks from Fireflies Autogenerated"

    deleted_cards = 0
    deleted_boards = Set.new

    fireflies_tasks.find_each do |imported_task|
      if imported_task.card
        board = imported_task.card.board
        card_number = imported_task.card.number
        
        begin
          imported_task.card.destroy!
          deleted_cards += 1
          deleted_boards << board.id
          puts "  ✓ Deleted card ##{card_number} from board '#{board.name}'"
        rescue => e
          puts "  ✗ Error deleting card ##{card_number}: #{e.message}"
        end
      end
      
      # Delete the imported task record
      imported_task.destroy!
    end

    # Check if any boards are now empty and can be deleted
    deleted_board_count = 0
    deleted_boards.each do |board_id|
      board = Board.find_by(id: board_id)
      next unless board
      
      if board.cards.count == 0
        begin
          board_name = board.name
          board.destroy!
          deleted_board_count += 1
          puts "  ✓ Deleted empty board '#{board_name}'"
        rescue => e
          puts "  ✗ Error deleting board '#{board.name}': #{e.message}"
        end
      end
    end

    Current.user = old_current_user

    puts ""
    puts "✅ Cleanup completed!"
    puts "  Deleted cards: #{deleted_cards}"
    puts "  Deleted boards: #{deleted_board_count}"
    puts "  Remaining Fireflies tasks: #{ImportedClickupTask.where(account: account).where('LOWER(list_name) LIKE ?', '%fireflies%').where('LOWER(list_name) LIKE ?', '%autogenerated%').count}"
  end
end
